---
  - name: Apt key
    become: true
    apt_key:
      id: E52529D4
      keyserver: keyserver.ubuntu.com:80
      state: present
    tags: install

  - name: Add apt repo
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
      state: present
    tags: install

  - name: Update and install mongo
    apt:
      force_apt_get: yes
      state: present
      update_cache: yes
      name: mongodb-org
    tags: install

  - name: Enable Mongo
    systemd:
      name: mongod
      enabled: yes
      state: started
    tags: install
...
